version: "2"

services:
  nodejs:
    image: node:8.11
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig
    working_dir: /app
    entrypoint: yarn start
    restart: always